// Placeholder until Database type is correctly imported/defined
// This assumes a similar structure to what might be generated by Supabase CLI
interface PlaceholderDatabase {
  public: {
    Tables: {
      photos: {
        Row: {
          id: string;
          url: string;
          thumbnail_url: string | null;
          alt_text: string;
          visible: boolean;
          created_at: string;
          updated_at: string;
          title: string | null;
          description: string | null;
          year: number | null;
        };
      };
      albums: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          cover_photo_id: string | null;
          visible: boolean | null;
          order_number: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
      };
    };
  };
}

// Using the placeholder type
type PhotoRow = PlaceholderDatabase['public']['Tables']['photos']['Row'];
type AlbumRow = PlaceholderDatabase['public']['Tables']['albums']['Row'];

export interface Photo extends PhotoRow {}

export interface Album extends AlbumRow {} 