name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint
      
      - name: Run type check
        run: npx tsc --noEmit
      
      - name: Run tests
        run: npm test -- --coverage
      
      - name: Upload coverage to Codecov
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
      
      - name: Check coverage threshold
        if: matrix.node-version == '20.x'
        run: |
          if [ -f coverage/coverage-summary.json ]; then
            COVERAGE=$(node -p "require('./coverage/coverage-summary.json').total.lines.pct")
            echo "Coverage: $COVERAGE%"
            if (( $(echo "$COVERAGE < 75" | bc -l) )); then
              echo "⚠️  Coverage $COVERAGE% is below threshold 75%"
              echo "This is a warning, not failing the build yet"
            else
              echo "✅ Coverage $COVERAGE% meets threshold"
            fi
          fi
      
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            coverage/
            test-results/